# Generated by Django 4.2.4 on 2023-09-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0007_video_gallery'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
