# Generated by Django 4.2.4 on 2024-02-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0013_alter_user_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('other', 'Other')], default='2022', max_length=100),
        ),
    ]
