# Generated by Django 4.2.4 on 2024-02-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0015_alter_category_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='year',
            new_name='year_field',
        ),
    ]
