# Generated by Django 4.2.4 on 2024-02-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0017_remove_category_year_field_category_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='year',
        ),
        migrations.AddField(
            model_name='category',
            name='year_field',
            field=models.IntegerField(choices=[(2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030')], default=2022, max_length=100),
        ),
    ]
