# Generated by Django 4.2.4 on 2024-02-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpMembers', '0018_remove_category_year_category_year_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='year_field',
        ),
        migrations.AddField(
            model_name='category',
            name='year',
            field=models.CharField(choices=[('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('other', 'Other')], default='2022', max_length=100),
        ),
    ]
